'use strict'

//item data
const items = [
  {
    itemListName:
      'IBIS Titanium Racing Road Bike USA SEBASTOPOL 56cm Made in California',
    description:
      'Ibis TI Bike, highly collectible, Superb titanium tube set, superb ride, 56CM top tube, semi sloping geo. 52cm seat tube. FYI, I am keeping the saddle, wheel set and pedals for my other bike.Questions welcomed.',
    itemType: 'Offer',
    itemCondition: 'Used',
    status: 'Closed',
    deliveryOption: 'Pickup_Only',
    createdAt: '2021-03-25 01:00:06',
    itemIdTEMP: 1,
    userIDTEMP: 1,
  },
  {
    itemListName: 'Stove and pan',
    description:
      'Another family member left this 15 years ago and does not want it back. I don’t have matching lid to go with the pan. Please email me with a possible pickup time.',
    itemType: 'Offer',
    itemCondition: 'Used',
    status: 'Open',
    deliveryOption: 'Pickup_Only',
    createdAt: '2021-03-22 01:00:06',
    itemIdTEMP: 2,
    userIDTEMP: 2,
  },
  {
    itemListName: 'Queen bed frame and duvet',
    description:
      " A queen metal bedframe. Also duvet + cover + pillow. No mattress. The duvet has only been lightly used and are only several months old / the duvet cover just needs a regular wash in the laundry. I would have kept them but I needed to move fast and wasn't able to take them with me.",
    itemType: 'Offer',
    itemCondition: 'Used',
    status: 'Open',
    deliveryOption: 'Pickup_Only',
    createdAt: '2021-03-26 03:00:06',
    itemIdTEMP: 3,
    userIDTEMP: 3,
  },
  {
    itemListName: 'Fancy watch',
    description:
      'Fancy Watcg in good condition. It comes with the box and a dust bag. Worn once.',
    itemType: 'Offer',
    itemCondition: 'Gently_Used',
    status: 'Open',
    deliveryOption: 'Pickup_Only',
    createdAt: '2021-03-24 05:00:06',
    itemIdTEMP: 4,
    userIDTEMP: 4,
  },
  {
    itemListName: 'HikingBoots',
    description: 'ISO of Hiking Boots for my summer vacation!. Size 38.',
    itemType: 'Seeking',
    itemCondition: 'Gently_Used',
    status: 'Open',
    deliveryOption: 'No_Contact_Pickup',
    createdAt: '2021-03-25 01:00:06',
    itemIdTEMP: 5,
    userIDTEMP: 5,
  },
  {
    itemListName: 'FREE 87 REGAL AFT CABIN-NEEDS MOTOR',
    description:
      '87 REGAL 23 FT. NEEDS MOTOR. FULL V CABIN PLUS AFT CABIN! SLEEPS 6!! ,FRIDGE SINK,STOVE,FULL HEAD WITH TANK! JUST BOTTOM PAINTED 5 YR PAINT! Never got around to putting in an engine and was just going to donate to make room for my other boat. hard to work with the charitable org. during this pandemic so I figured I give it a shot to sell for same as donation. If you Know way around boats could pick up a deal. Boat is in water and would have to pick it up at nearby ramp.Very LOCAL Water delivery also possible. Thanks.',
    itemType: 'Offer',
    itemCondition: 'Used',
    status: 'Open',
    deliveryOption: 'Will_Deliver',
    createdAt: '2021-03-26 01:00:06',
    itemIdTEMP: 6,
    userIDTEMP: 6,
  },
  {
    itemListName: 'Bike',
    description: 'ISO of Bike',
    itemType: 'Seeking',
    itemCondition: 'Used',
    status: 'Open',
    deliveryOption: 'No_Contact_Pickup',
    createdAt: '2021-03-24 05:00:06',
    itemIdTEMP: 7,
    userIDTEMP: 1,
  },
  {
    itemListName: 'Bike Helmet',
    description: 'ISO - Bike Helmet',
    itemType: 'Seeking',
    itemCondition: 'New',
    status: 'Open',
    deliveryOption: 'No_Contact_Pickup',
    createdAt: '2021-03-26 01:00:06',
    itemIdTEMP: 8,
    userIDTEMP: 2,
  },
  {
    itemListName: 'A puppy',
    description: 'ISO of cute puppy - prefer a pug',
    itemType: 'Seeking',
    itemCondition: 'New',
    status: 'Open',
    deliveryOption: 'Pickup_Only',
    createdAt: '2021-03-25 01:00:06',
    itemIdTEMP: 9,
    userIDTEMP: 3,
  },
  {
    itemListName: 'Baby swing ',
    description: 'Battery operated Eddie Bauer baby swing. Works.',
    itemType: 'Offer',
    itemCondition: 'Used',
    status: 'Open',
    deliveryOption: 'Pickup_Only',
    createdAt: '2021-03-26 01:00:06',
    itemIdTEMP: 10,
    userIDTEMP: 4,
  },
  {
    itemListName: "Baldwin 5'1 BG Piano",
    description:
      "Hi everyone, how are you all doing today?.. Hope your day started well...Am giving out a Baldwin 5'1 Baby Grand Piano out for free to a very passionate lover who will take good card of this beautiful baby... If interested, please do drop me a phone number so i can contact you. Thanks.",
    itemType: 'Offer',
    itemCondition: 'Gently_Used',
    status: 'Open',
    deliveryOption: 'Pickup_Only',
    createdAt: '2021-03-26 01:00:06',
    itemIdTEMP: 11,
    userIDTEMP: 5,
  },
]
module.exports = items
