'use strict'

//userData
const users = [
  {
    firstName: 'Diego',
    middleName: '',
    lastName: 'Abreu',
    email: 'diego@mail.com',
    admin: true,
    password: 'password',
    street1: '721 E 182nd St',
    street2: '',
    city: 'Bronx',
    state: 'NY',
    zip: 10457,
    latitude: 40.85026804,
    longitude: -73.88580684,
    userIdTEMP: 1,
  },
  {
    firstName: 'Melinda',
    middleName: '',
    lastName: 'Armbruster',
    email: 'melinda@mail.com',
    admin: false,
    password: 'password',
    street1: '31 Saint Johns Pl',
    street2: '',
    city: 'Brooklyn',
    state: 'NY',
    zip: 11217,
    latitude: 40.67824,
    longitude: -73.97802,
    userIdTEMP: 2,
  },
  {
    firstName: 'Yoshie',
    middleName: '',
    lastName: 'Fujiwara',
    email: 'yoshie@mail.com',
    admin: false,
    password: 'password',
    street1: '115 Broadway',
    street2: '3A',
    city: 'New York',
    state: 'NY',
    zip: 10006,
    latitude: 40.708832,
    longitude: -74.011497,
    userIdTEMP: 3,
  },
  {
    firstName: 'Jae',
    middleName: '',
    lastName: 'Chung',
    email: 'jae@mail.com',
    admin: true,
    password: 'password',
    street1: '222 E 93rd St',
    street2: '#APT 11C',
    city: 'New York',
    state: 'NY',
    zip: 10002,
    latitude: 40.78231,
    longitude: -73.94947,
    userIdTEMP: 4,
  },
  {
    firstName: 'Arthur',
    middleName: '',
    lastName: 'Bennett',
    email: 'a.bennett@randatmail.com',
    admin: false,
    password: 'password',
    street1: '127 3rd St',
    street2: '',
    city: 'Staten Island',
    state: 'NY',
    zip: 10306,
    latitude: 40.5745872,
    longitude: -74.1190681,
    userIdTEMP: 5,
  },
  {
    firstName: 'Charlie',
    middleName: '',
    lastName: 'Taylor',
    email: 'c.taylor@randatmail.com',
    admin: false,
    password: 'password',
    street1: '115 Halsey St',
    street2: '',
    city: 'Brooklyn',
    state: 'NY',
    zip: 11216,
    latitude: 40.68212698,
    longitude: -73.94902954,
    userIdTEMP: 6,
  },
]
module.exports = users
