'use strict'

//userData
const users = [
  {
    firstName: 'Diego',
    middleName: '',
    lastName: 'Abreu',
    email: 'diego@mail.com',
    admin: true,
    password: 'password',
    street1: '721 E 182nd St',
    street2: '',
    city: 'Bronx',
    state: 'NY',
    zip: 10457,
    latitude: 40.85026804,
    longitude: -73.88580684,
  },
  {
    firstName: 'Melinda',
    middleName: '',
    lastName: 'Armbruster',
    email: 'melinda@mail.com',
    admin: false,
    password: 'password',
    street1: '31 Saint Johns Pl',
    street2: '',
    city: 'Brooklyn',
    state: 'NY',
    zip: 11217,
    latitude: 40.67824,
    longitude: -73.97802,
  },
  {
    firstName: 'Yoshie',
    middleName: '',
    lastName: 'Fujiwara',
    email: 'yoshie@mail.com',
    admin: false,
    password: 'password',
    street1: '115 Broadway',
    street2: '3A',
    city: 'New York',
    state: 'NY',
    zip: 10006,
    latitude: 40.708832,
    longitude: -74.011497,
  },
  {
    firstName: 'Jae',
    middleName: '',
    lastName: 'Chung',
    email: 'jae@mail.com',
    admin: true,
    password: 'password',
    street1: '222 E 93rd St',
    street2: '#APT 11C',
    city: 'New York',
    state: 'NY',
    zip: 10002,
    latitude: 40.78231,
    longitude: -73.94947,
  },
  {
    firstName: 'Arthur',
    middleName: '',
    lastName: 'Bennett',
    email: 'a.bennett@randatmail.com',
    admin: false,
    password: 'password',
    street1: '127 3rd St',
    street2: '',
    city: 'Staten Island',
    state: 'NY',
    zip: 10306,
    latitude: 40.5745872,
    longitude: -74.1190681,
  },
  {
    firstName: 'Charlie',
    middleName: '',
    lastName: 'Taylor',
    email: 'c.taylor@randatmail.com',
    admin: false,
    password: 'password',
    street1: '115 Halsey St',
    street2: '',
    city: 'Brooklyn',
    state: 'NY',
    zip: 11216,
    latitude: 40.68212698,
    longitude: -73.94902954,
  },
  {
    firstName: 'David',
    middleName: '',
    lastName: 'Brown',
    email: 'd.brown@randatmail.com',
    admin: false,
    password: 'password',
    street1: '718 Garden St',
    street2: '',
    city: 'Bronx',
    state: 'NY',
    zip: 10457,
    latitude: 40.85030806,
    longitude: -73.8852769,
  },
  {
    firstName: 'Oliver',
    middleName: '',
    lastName: 'Dixon',
    email: 'o.dixon@randatmail.com',
    admin: false,
    password: 'password',
    street1: '640 Amsterdam Ave',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10025,
    latitude: 40.79114969,
    longitude: -73.97292461,
  },
  {
    firstName: 'Frederick',
    middleName: '',
    lastName: 'Barrett',
    email: 'f.barrett@randatmail.com',
    admin: false,
    password: 'password',
    street1: '136 W 88th St\n',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10024,
    latitude: 40.78812432,
    longitude: -73.9723958,
  },
  {
    firstName: 'Kristian',
    middleName: '',
    lastName: 'Richards',
    email: 'k.richards@randatmail.com',
    admin: false,
    password: 'password',
    street1: '18 129th St',
    street2: '',
    city: 'College Point',
    state: 'NY',
    zip: 11356,
    latitude: 40.7821148,
    longitude: -73.83979424,
  },
  {
    firstName: 'Caroline',
    middleName: '',
    lastName: 'Hunt',
    email: 'c.hunt@randatmail.com',
    admin: false,
    password: 'password',
    street1: '127 18th Ave',
    street2: '',
    city: 'College Point',
    state: 'NY',
    zip: 11356,
    latitude: 40.78341558,
    longitude: -73.84180089,
  },
  {
    firstName: 'Myra',
    middleName: '',
    lastName: 'Moore',
    email: 'm.moore@randatmail.com',
    admin: false,
    password: 'password',
    street1: '151 11th Ave',
    street2: '',
    city: 'Flushing',
    state: 'NY',
    zip: 11357,
    latitude: 40.7920588,
    longitude: -73.81115419,
  },
  {
    firstName: 'Harold',
    middleName: '',
    lastName: 'Stewart',
    email: 'h.stewart@randatmail.com',
    admin: false,
    password: 'password',
    street1: '210 Buttrick Ave',
    street2: '',
    city: 'Bronx',
    state: 'NY',
    zip: 10465,
    latitude: 40.81369326,
    longitude: -73.82324837,
  },
  {
    firstName: 'Nicholas',
    middleName: '',
    lastName: 'Roberts',
    email: 'n.roberts@randatmail.com',
    admin: false,
    password: 'password',
    street1: '43 Delphine Terrace',
    street2: '',
    city: 'Staten Island',
    state: 'NY',
    zip: 10305,
    latitude: 40.60329312,
    longitude: -74.08023413,
  },
  {
    firstName: 'Rebecca',
    middleName: '',
    lastName: 'Williams',
    email: 'r.williams@randatmail.com',
    admin: false,
    password: 'password',
    street1: '239 St Johns Ave',
    street2: '',
    city: 'Staten Island',
    state: 'NY',
    zip: 10305,
    latitude: 40.60903749,
    longitude: -74.07167198,
  },
  {
    firstName: 'Ellia',
    middleName: '',
    lastName: 'Richards',
    email: 'e.richards@randatmail.com',
    admin: false,
    password: 'password',
    street1: '460 Degraw Stx',
    street2: '',
    city: 'Brooklyn',
    state: 'NY',
    zip: 11217,
    latitude: 40.68147,
    longitude: -73.98948621,
  },
  {
    firstName: 'Alissa',
    middleName: '',
    lastName: 'Davis',
    email: 'a.davis@randatmail.com',
    admin: false,
    password: 'password',
    street1: '251 Hoyt St',
    street2: '',
    city: 'Brooklyn',
    state: 'NY',
    zip: 11217,
    latitude: 40.68245696,
    longitude: -73.99041711,
  },
  {
    firstName: 'Charlotte',
    middleName: '',
    lastName: 'Stevens',
    email: 'c.stevens@randatmail.com',
    admin: false,
    password: 'password',
    street1: '38 King St',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10014,
    latitude: 40.72763317,
    longitude: -74.00423755,
  },
  {
    firstName: 'Rubie',
    middleName: '',
    lastName: 'Howard',
    email: 'r.howard@randatmail.com',
    admin: false,
    password: 'password',
    street1: '71 Reade St',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10007,
    latitude: 40.71495823,
    longitude: -74.00702982,
  },
  {
    firstName: 'Eleanor',
    middleName: '',
    lastName: 'Mason',
    email: 'e.mason@randatmail.com',
    admin: false,
    password: 'password',
    street1: '17 Cedar St',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10005,
    latitude: 40.70699519,
    longitude: -74.00791953,
  },
  {
    firstName: 'Joyce',
    middleName: '',
    lastName: 'Robinson',
    email: 'j.robinson@randatmail.com',
    admin: false,
    password: 'password',
    street1: '18 Leroy Stx',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10014,
    latitude: 40.73062569,
    longitude: -74.00341346,
  },
  {
    firstName: 'Tess',
    middleName: '',
    lastName: 'Morrison',
    email: 't.morrison@randatmail.com',
    admin: false,
    password: 'password',
    street1: '41 Grove St',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10014,
    latitude: 40.73298196,
    longitude: -74.00444176,
  },
  {
    firstName: 'Walter',
    middleName: '',
    lastName: 'Campbell',
    email: 'w.campbell@randatmail.com',
    admin: false,
    password: 'password',
    street1: '23 W 31st St',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10001,
    latitude: 40.74724191,
    longitude: -73.98715983,
  },
  {
    firstName: 'Albert',
    middleName: '',
    lastName: 'Brooks',
    email: 'a.brooks@randatmail.com',
    admin: false,
    password: 'password',
    street1: '117 E 38th St',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10016,
    latitude: 40.74934122,
    longitude: -73.97828985,
  },
  {
    firstName: 'Rosie',
    middleName: '',
    lastName: 'Harper',
    email: 'r.harper@randatmail.com',
    admin: false,
    password: 'password',
    street1: '234 E 67th St',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10065,
    latitude: 40.76579066,
    longitude: -73.96154113,
  },
  {
    firstName: 'Dexter',
    middleName: '',
    lastName: 'Wilson',
    email: 'd.wilson@randatmail.com',
    admin: false,
    password: 'password',
    street1: '123 E 71st St',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10021,
    latitude: 40.77018318,
    longitude: -73.96324759,
  },
  {
    firstName: 'Lydia',
    middleName: '',
    lastName: 'Richards',
    email: 'l.richards@randatmail.com',
    admin: false,
    password: 'password',
    street1: '166 W 123rd St',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10027,
    latitude: 40.80731246,
    longitude: -73.94883973,
  },
  {
    firstName: 'Joyce',
    middleName: '',
    lastName: 'Perkins',
    email: 'j.perkins@randatmail.com',
    admin: false,
    password: 'password',
    street1: '1626 Amsterdam Ave',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10031,
    latitude: 40.82251695,
    longitude: -73.95005991,
  },
  {
    firstName: 'Dale',
    middleName: '',
    lastName: 'Kelley',
    email: 'd.kelley@randatmail.com',
    admin: false,
    password: 'password',
    street1: '61 Haven Ave',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10032,
    latitude: 40.84348321,
    longitude: -73.9426517,
  },
  {
    firstName: 'Jasmine',
    middleName: '',
    lastName: 'Foster',
    email: 'j.foster@randatmail.com',
    admin: false,
    password: 'password',
    street1: '596 Beech Terrace',
    street2: '',
    city: 'Bronx',
    state: 'NY',
    zip: 10454,
    latitude: 40.80948364,
    longitude: -73.91440187,
  },
  {
    firstName: 'Owen',
    middleName: '',
    lastName: 'Armstrong',
    email: 'o.armstrong@randatmail.com',
    admin: false,
    password: 'password',
    street1: '758 E 152nd St',
    street2: '',
    city: 'Bronx',
    state: 'NY',
    zip: 10455,
    latitude: 40.81556151,
    longitude: -73.90677843,
  },
  {
    firstName: 'Chelsea',
    middleName: '',
    lastName: 'Evans',
    email: 'c.evans@randatmail.com',
    admin: false,
    password: 'password',
    street1: '1223 Grand Concourse,',
    street2: '',
    city: 'Bronx',
    state: 'NY',
    zip: 10452,
    latitude: 40.83504538,
    longitude: -73.91756003,
  },
  {
    firstName: 'Adele',
    middleName: '',
    lastName: 'Edwards',
    email: 'a.edwards@randatmail.com',
    admin: false,
    password: 'password',
    street1: '1470 E 18th St',
    street2: '',
    city: 'Brooklyn',
    state: 'NY',
    zip: 11230,
    latitude: 40.61458122,
    longitude: -73.95671895,
  },
  {
    firstName: 'Briony',
    middleName: '',
    lastName: 'Lloyd',
    email: 'b.lloyd@randatmail.com',
    admin: false,
    password: 'password',
    street1: '1377 East 16th Street',
    street2: '',
    city: 'Brooklyn',
    state: 'NY',
    zip: 11230,
    latitude: 40.61635063,
    longitude: -73.95847355,
  },
  {
    firstName: 'Blake',
    middleName: '',
    lastName: 'Kelly',
    email: 'b.kelly@randatmail.com',
    admin: false,
    password: 'password',
    street1: '597 Rogers Ave',
    street2: '',
    city: 'Brooklyn',
    state: 'NY',
    zip: 11225,
    latitude: 40.65721763,
    longitude: -73.95288983,
  },
  {
    firstName: 'Agata',
    middleName: '',
    lastName: 'Turner',
    email: 'a.turner@randatmail.com',
    admin: false,
    password: 'password',
    street1: '5426 69th St',
    street2: '',
    city: 'Maspeth',
    state: 'NY',
    zip: 11378,
    latitude: 40.72830712,
    longitude: -73.89586322,
  },
]
module.exports = users
