'use strict'

//userData
const users = [
  {
    firstName: 'Diego',
    middleName: '',
    lastName: 'Abreu',
    email: 'diego@mail.com',
    admin: true,
    password: 'password',
    street1: '3328 Tiemann Ave',
    street2: '',
    city: 'Bronx',
    state: 'NY',
    zip: 10469,
    latitude: 40.87645,
    longitude: -73.84273,
  },
  {
    firstName: 'Melinda',
    middleName: '',
    lastName: 'Armbruster',
    email: 'melinda@mail.com',
    admin: false,
    password: 'password',
    street1: '31 Saint Johns Pl',
    street2: '',
    city: 'Brooklyn',
    state: 'NY',
    zip: 11217,
    latitude: 40.67824,
    longitude: -73.97802,
  },
  {
    firstName: 'Yoshie',
    middleName: '',
    lastName: 'Fujiwara',
    email: 'yoshie@mail.com',
    admin: false,
    password: 'password',
    street1: '115 Broadway',
    street2: '3A',
    city: 'New York',
    state: 'NY',
    zip: 10006,
    latitude: 40.708832,
    longitude: -74.011497,
  },
  {
    firstName: 'Jae',
    middleName: '',
    lastName: 'Chung',
    email: 'jae@mail.com',
    admin: true,
    password: 'password',
    street1: '222 E 93rd St',
    street2: '#APT 11C',
    city: 'New York',
    state: 'NY',
    zip: 10002,
    latitude: 40.78231,
    longitude: -73.94947,
  },
  {
    firstName: 'Arthur',
    middleName: '',
    lastName: 'Bennett',
    email: 'a.bennett@randatmail.com',
    admin: false,
    password: 'password',
    street1: '51 East Fairground St.\n',
    street2: '',
    city: 'Staten Island',
    state: 'NY',
    zip: 10306,
    latitude: 40.60984,
    longitude: -74.12103,
  },
  {
    firstName: 'Charlie',
    middleName: '',
    lastName: 'Taylor',
    email: 'c.taylor@randatmail.com',
    admin: false,
    password: 'password',
    street1: '25 Magnolia Dr',
    street2: '',
    city: 'Brooklyn',
    state: 'NY',
    zip: 11237,
    latitude: 40.74816,
    longitude: -73.67926,
  },
  {
    firstName: 'David',
    middleName: '',
    lastName: 'Brown',
    email: 'd.brown@randatmail.com',
    admin: false,
    password: 'password',
    street1: '19 Airport Lane',
    street2: '',
    city: 'Bronx',
    state: 'NY',
    zip: 10458,
    latitude: 41.40696,
    longitude: -74.53193,
  },
  {
    firstName: 'Oliver',
    middleName: '',
    lastName: 'Dixon',
    email: 'o.dixon@randatmail.com',
    admin: false,
    password: 'password',
    street1: '9257 Devonshire St.',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10025,
    latitude: 40.81732,
    longitude: -73.19645,
  },
  {
    firstName: 'Frederick',
    middleName: '',
    lastName: 'Barrett',
    email: 'f.barrett@randatmail.com',
    admin: false,
    password: 'password',
    street1: '118 Newbridge Drive\n',
    street2: '',
    city: 'New York',
    state: 'NY',
    zip: 10003,
    latitude: 40.71197,
    longitude: -73.54417,
  },
]
module.exports = users
